<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <WarningLevel>9999</WarningLevel>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <WarningLevel>9999</WarningLevel>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Network\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenAI\OpenAI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management.Automation">
      <HintPath>..\System.Management.Automation.dll</HintPath>
    </Reference>
  </ItemGroup>


</Project>
